# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NDH Development Agency
email: nicholasdkline@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nick David's Holistic Development Agentcy specializes in developing web applications, user interfaces, and marketing strategies, through a holistic approach to development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nickdavidsholisticdevelopmentagency.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
roles: 
  - Systems Integration
  - UI/UX Design
  - Marketing
  - Business Strategy 
  - App Development 

# Build settings
markdown: kramdown
destination: docs
#theme: minima
plugins:
  - jekyll-toc
  - jekyll-paginate
  - jekyll-sitemap

collections:
  clients:
    output: true
    permalink: /:collection/:name
  
links:
  robinhood: http://share.robinhood.com/nicholk168

permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page:num/" 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
